<a href="https://colab.research.google.com/github/JorgeHdzRiv/Program-neural-networks-with-TensorFlow/blob/main/Introduccion_MachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduccion al Machine Learning
Considera los siguientes conjuntos de números. ¿Puedes ver la relación entre ellas?

X: -1 0 1 2 3 4

---

Y: -2 1 4 7 10 13

---
Si las observas, notarás que el valor de X aumenta en 1 a medida que lees de izquierda a derecha, y el valor correspondiente de Y está aumentando en 3. Es probable que creas que Y es igual a 3 veces mayor o menor que algo. Es probable que observes el 0 en X y veas que Y es 1, y determinas la relación Y=3X+1.

Eso es casi exactamente cómo usarías el código para entrenar un modelo a fin de detectar los patrones en los datos.

Ahora mira el código para hacerlo.

¿Cómo se debería entrenar una red neuronal para que realice la tarea equivalente? Usando datos Al alimentarlo con un conjunto de X y un conjunto de Y, debería poder determinar la relación entre ellos.


## Importaciones
Comienza con tus importaciones. Aquí, importarás TensorFlow y lo llamarás tf para facilitar el uso.

A continuación, importa una biblioteca llamada numpy, que representa tus datos como listas de manera fácil y rápida.

El framework para definir una red neuronal como un conjunto de capas secuenciales se denomina keras, así que importa eso también.

In [2]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

## Definir y compilar la red neuronal
A continuación, cree la red neuronal más simple posible. Tiene una capa, esa capa tiene una neurona, y la forma de entrada de esta es solo un valor.

In [3]:
model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])
model

A continuación, escribe el código para compilar tu red neuronal. Cuando lo hagas, debes especificar dos funciones: **loss** y **optimizer**.

En este ejemplo, sabe que la relación entre los números es **Y=3X+1**.

Cuando la computadora intenta aprender eso, hace una conjetura, quizás Y=10X+10. La función **loss** mide las respuestas que adivinó en comparación con las respuestas correctas conocidas y mide el rendimiento de la respuesta.

A continuación, el modelo usa la función **optimizer** para hacer otra estimación. Según la función de pérdida, intenta minimizar la pérdida. En este punto, quizá surge algo con Y=5X+5. Si bien eso es bastante malo, se encuentra más cerca del resultado correcto (la pérdida es menor).

El modelo se repite durante la cantidad de épocas, que verás en breve.

Primero, veamos cómo indicarle que use **mean_squared_error** para la pérdida y el **descenso de gradientes estocástico (sgd)** para el optimizador. No es necesario que comprendas los cálculos, ya que puedes ver que funcionan.

Con el tiempo, aprenderás las diferentes funciones de pérdida y optimizador, y las adecuadas para diferentes situaciones.

In [4]:
model.compile(optimizer='sgd', loss='mean_squared_error')

## Proporcionar los datos
A continuación, ingresa algunos datos. En este caso, tome las seis variables X y Y anteriores. Puede ver que la relación entre ellos es que Y=3X+1, en donde X es -1, Y es -2.

Para hacerlo, se usa una biblioteca de Python llamada NumPy, que proporciona muchas estructuras de datos de tipo array. Especifica los valores como un arreglo en NumPy con np.array[].

In [5]:
xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-2.0, 1.0, 4.0, 7.0, 10.0, 13.0], dtype=float)

In [6]:
xs,ys

(array([-1.,  0.,  1.,  2.,  3.,  4.]), array([-2.,  1.,  4.,  7., 10., 13.]))

# Entrenamiento de la red neuronal
El proceso de entrenamiento de la red neuronal, donde aprende la relación entre las X y las Y, está en la llamada model.fit. En este punto, pasará por el bucle antes de hacer una conjetura, medir lo bueno o malo que es (la pérdida) o usar el optimizador para hacer otra estimación. Hará eso durante el número de ciclos de entrenamiento que especifiques. Cuando ejecutes ese código, verás que la pérdida se imprimirá para cada época.

In [7]:
model.fit?

#Trains the model for a fixed number of epochs (iterations on a dataset).

In [8]:
#Entrenando el modelo
model.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 433ms/step - loss: 76.0674
Epoch 2/500
1/1 [==============================] - 0s 7ms/step - loss: 59.8479
Epoch 3/500
1/1 [==============================] - 0s 8ms/step - loss: 47.0872
Epoch 4/500
1/1 [==============================] - 0s 8ms/step - loss: 37.0476
Epoch 5/500
1/1 [==============================] - 0s 9ms/step - loss: 29.1489
Epoch 6/500
1/1 [==============================] - 0s 8ms/step - loss: 22.9346
Epoch 7/500
1/1 [==============================] - 0s 10ms/step - loss: 18.0454
Epoch 8/500
1/1 [==============================] - 0s 9ms/step - loss: 14.1988
Epoch 9/500
1/1 [==============================] - 0s 9ms/step - loss: 11.1724
Epoch 10/500
1/1 [==============================] - 0s 10ms/step - loss: 8.7914
Epoch 11/500
1/1 [==============================] - 0s 15ms/step - loss: 6.9181
Epoch 12/500
1/1 [==============================] - 0s 9ms/step - loss: 5.4443
Epoch 13/500
1/1 [=============================

Por ejemplo, puedes ver que, durante las primeras etapas, el valor de pérdida es bastante grande, pero se hace más pequeño con cada paso.

A medida que avanza el entrenamiento, la pérdida pronto se vuelve muy pequeña.

Para el momento en que se completa el entrenamiento, la pérdida es muy pequeña, lo que demuestra que nuestro modelo está haciendo un excelente trabajo para inferir la relación entre los números.

Probablemente no necesites los 500 ciclos de entrenamiento y puedes experimentar con distintas cantidades. Como puedes ver en el ejemplo, la pérdida es muy pequeña después de solo 50 ciclos de entrenamiento, por lo que eso podría ser suficiente.

In [9]:
#Probando el modelo con menos interacciones
model.fit(xs,ys,epochs=50)

Epoch 1/50
1/1 [==============================] - 0s 16ms/step - loss: 2.8288e-07
Epoch 2/50
1/1 [==============================] - 0s 14ms/step - loss: 2.7707e-07
Epoch 3/50
1/1 [==============================] - 0s 10ms/step - loss: 2.7138e-07
Epoch 4/50
1/1 [==============================] - 0s 6ms/step - loss: 2.6579e-07
Epoch 5/50
1/1 [==============================] - 0s 5ms/step - loss: 2.6030e-07
Epoch 6/50
1/1 [==============================] - 0s 6ms/step - loss: 2.5498e-07
Epoch 7/50
1/1 [==============================] - 0s 7ms/step - loss: 2.4973e-07
Epoch 8/50
1/1 [==============================] - 0s 4ms/step - loss: 2.4462e-07
Epoch 9/50
1/1 [==============================] - 0s 8ms/step - loss: 2.3964e-07
Epoch 10/50
1/1 [==============================] - 0s 8ms/step - loss: 2.3470e-07
Epoch 11/50
1/1 [==============================] - 0s 8ms/step - loss: 2.2988e-07
Epoch 12/50
1/1 [==============================] - 0s 7ms/step - loss: 2.2510e-07
Epoch 13/50
1/1 [=====

# Usando el modelo
Tiene un modelo que se entrenó para aprender la relación entre X e Y. Puedes usar el método model.predict para que averigüe la Y para una X desconocida. Por ejemplo, si X es 10, ¿cuál crees que será Y? Antes de ejecutar el siguiente código, adivina:


In [10]:
#Prediciendo el resultado del modelo para la funcion Y=3X+10 de acuerdo al modelo
print(model.predict([10.0]))
#Resultado esperado 31.0

[[30.999063]]


Tal vez pensaste en 31, pero el resultado fue un poco más. ¿Por qué creé que pasó esto?

Las redes neuronales se ocupan de las probabilidades, por lo que calculó que existe una alta probabilidad de que la relación entre X e Y sea Y=3X+1, pero no puede saberlo con seis datos. El resultado es muy cercano a 31, pero no necesariamente a 31.

A medida que trabajas con redes neuronales, verás que ese patrón es recurrente. Casi siempre abordarás las probabilidades, no las incertidumbres, y practicarás un poco de código a fin de determinar cuál es el resultado basado en las probabilidades, especialmente cuando se trata de clasificación.

# Adicional: Mejorando el modelo

Para la mejora de nuestro modelo haremos tres cosas

1. Proporcionar mas datos para las series x,y dado que son series sencillas
2. Optimizar el proceso con las epochs o interacciones necesarias
3. Observar los resultados

## Definimos nuevos arrays de datos mas completos basandonos en la funcion descrita Y=3x+1

Para ellos crearemos dos valores para que el usuario decida cuantos datos tendra el array

In [11]:
inicio = int(input("Valor de inicio del array X: "))
fin = int(input("Valor de fin del array Y: "))

X=np.arange(inicio,fin+1)
X

Valor de inicio del array X: -6
Valor de fin del array Y: 6


array([-6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [12]:
#Creacion del array Y
Y=np.array((3*X)+1)
Y

array([-17, -14, -11,  -8,  -5,  -2,   1,   4,   7,  10,  13,  16,  19])

## Creacion de un nuevo modelo


In [13]:
beta = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

## Optimizacion del modelo

In [14]:
beta.compile(optimizer='sgd', loss='mean_squared_error')

## Creando la red y entrenandola

In [15]:
beta.fit(X,Y, epochs=200)

Epoch 1/200
1/1 [==============================] - 0s 235ms/step - loss: 111.3950
Epoch 2/200
1/1 [==============================] - 0s 7ms/step - loss: 58.1892
Epoch 3/200
1/1 [==============================] - 0s 5ms/step - loss: 30.5898
Epoch 4/200
1/1 [==============================] - 0s 6ms/step - loss: 16.2654
Epoch 5/200
1/1 [==============================] - 0s 5ms/step - loss: 8.8235
Epoch 6/200
1/1 [==============================] - 0s 5ms/step - loss: 4.9502
Epoch 7/200
1/1 [==============================] - 0s 5ms/step - loss: 2.9273
Epoch 8/200
1/1 [==============================] - 0s 6ms/step - loss: 1.8644
Epoch 9/200
1/1 [==============================] - 0s 5ms/step - loss: 1.2996
Epoch 10/200
1/1 [==============================] - 0s 5ms/step - loss: 0.9936
Epoch 11/200
1/1 [==============================] - 0s 5ms/step - loss: 0.8223
Epoch 12/200
1/1 [==============================] - 0s 5ms/step - loss: 0.7214
Epoch 13/200
1/1 [==============================] - 0s

## Probando nuestro modelo


In [16]:
print(beta.predict([10.0]))
#Resultado esperado 31 

[[30.98241]]


## Observaciones
Con 200 epochs el modelo es mas preciso pero aun no llega al resultado real esperado

En el codigo posterior se procedera a realizar 250 y probar nuevamente

In [17]:
beta.fit(X,Y,epochs=280)


Epoch 1/280
1/1 [==============================] - 0s 21ms/step - loss: 3.0933e-04
Epoch 2/280
1/1 [==============================] - 0s 5ms/step - loss: 2.9710e-04
Epoch 3/280
1/1 [==============================] - 0s 5ms/step - loss: 2.8532e-04
Epoch 4/280
1/1 [==============================] - 0s 5ms/step - loss: 2.7403e-04
Epoch 5/280
1/1 [==============================] - 0s 5ms/step - loss: 2.6317e-04
Epoch 6/280
1/1 [==============================] - 0s 10ms/step - loss: 2.5274e-04
Epoch 7/280
1/1 [==============================] - 0s 5ms/step - loss: 2.4275e-04
Epoch 8/280
1/1 [==============================] - 0s 9ms/step - loss: 2.3313e-04
Epoch 9/280
1/1 [==============================] - 0s 9ms/step - loss: 2.2390e-04
Epoch 10/280
1/1 [==============================] - 0s 9ms/step - loss: 2.1503e-04
Epoch 11/280
1/1 [==============================] - 0s 6ms/step - loss: 2.0652e-04
Epoch 12/280
1/1 [==============================] - 0s 5ms/step - loss: 1.9834e-04
Epoch 13/28

In [18]:
print(beta.predict([10.0]))

[[30.999937]]


## Pruebas finales

Procederemos a implementar funciones de numpy para mejorar el resultado de la prueba



In [19]:
prediccion = beta.predict([10.0])
#Resultado esperado 31

prediccion_final = float(np.ceil(prediccion))

prediccion_final

31.0

In [20]:
# Prueba con otro valor aleatorio

# Ejemplo de salida Y=3(15)+1  Y=46

prediccion = beta.predict([15.0])
#Resultado esperado 46
prediccion_final = float(np.ceil(prediccion))

prediccion_final

46.0